# Generated by Django 5.1.5 on 2025-02-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
